python benchmarks/satelite.py --retrain_shield
python benchmarks/dcmotor.py --retrain_shield
python benchmarks/tape.py --retrain_shield
python benchmarks/magnetic-pointer.py --retrain_shield
python benchmarks/suspension.py --retrain_shield
python benchmarks/biology.py --retrain_shield
python benchmarks/data-center-cooling.py --retrain_shield
python benchmarks/quadcopter.py --retrain_shield
python benchmarks/pendulum.py --retrain_shield
python benchmarks/cartpole.py --retrain_shield
python benchmarks/selfdriving.py --retrain_shield
python benchmarks/lanekeeping.py --retrain_shield
python benchmarks/4-car-platoon.py --retrain_shield
python benchmarks/8-car-platoon.py --retrain_shield
python benchmarks/oscillator.py --retrain_shield
python benchmarks/cartpole_change_l.py --retrain_shield
python benchmarks/pendulum_change_m.py --retrain_shield
python benchmarks/pendulum_change_l.py --retrain_shield
python benchmarks/selfdriving_obs.py --retrain_shield