python satelite.py --retrain_shield
python dcmotor.py --retrain_shield
python tape.py --retrain_shield
python magnetic-pointer.py --retrain_shield
python suspension.py --retrain_shield
python biology.py --retrain_shield
python data-center-cooling.py --retrain_shield
python quadcopter.py --retrain_shield
python pendulum.py --retrain_shield
python cartpole.py --retrain_shield
python selfdriving.py --retrain_shield
python lanekeeping.py --retrain_shield
python 4-car-platoon.py --retrain_shield
python 8-car-platoon.py --retrain_shield
python oscillator.py --retrain_shield
python cartpole_change_l.py --retrain_shield
python pendulum_change_m.py --retrain_shield
python pendulum_change_l.py --retrain_shield
python selfdriving_obs.py --retrain_shield