python benchmarks/satelite.py --nn_test --shield_test
python benchmarks/dcmotor.py --nn_test --shield_test
python benchmarks/tape.py --nn_test --shield_test
python benchmarks/magnetic-pointer.py --nn_test --shield_test
python benchmarks/suspension.py --nn_test --shield_test
python benchmarks/biology.py --nn_test --shield_test
python benchmarks/data-center-cooling.py --nn_test --shield_test
python benchmarks/quadcopter.py --nn_test --shield_test
python benchmarks/pendulum.py --nn_test --shield_test
python benchmarks/cartpole.py --nn_test --shield_test
python benchmarks/selfdriving.py --nn_test --shield_test
python benchmarks/lanekeeping.py --nn_test --shield_test
python benchmarks/4-car-platoon.py --nn_test --shield_test
python benchmarks/8-car-platoon.py --nn_test --shield_test
python benchmarks/oscillator.py --nn_test --shield_test
python benchmarks/cartpole_change_l.py --nn_test --shield_test
python benchmarks/pendulum_change_m.py --nn_test --shield_test
python benchmarks/pendulum_change_l.py --nn_test --shield_test
python benchmarks/selfdriving_obs.py --nn_test --shield_test