python benchmarks/satelite.py --retrain_nn
python benchmarks/dcmotor.py --retrain_nn
python benchmarks/tape.py --retrain_nn
python benchmarks/magnetic-pointer.py --retrain_nn
python benchmarks/suspension.py --retrain_nn
python benchmarks/biology.py --retrain_nn
python benchmarks/data-center-cooling.py --retrain_nn
python benchmarks/quadcopter.py --retrain_nn
python benchmarks/pendulum.py --retrain_nn
python benchmarks/cartpole.py --retrain_nn
python benchmarks/selfdriving.py --retrain_nn
python benchmarks/lanekeeping.py --retrain_nn
python benchmarks/4-car-platoon.py --retrain_nn
python benchmarks/8-car-platoon.py --retrain_nn
python benchmarks/oscillator.py --retrain_nn