python satelite.py --nn_test --shield_test
python dcmotor.py --nn_test --shield_test
python tape.py --nn_test --shield_test
python magnetic-pointer.py --nn_test --shield_test
python suspension.py --nn_test --shield_test
python biology.py --nn_test --shield_test
python data-center-cooling.py --nn_test --shield_test
python quadcopter.py --nn_test --shield_test
python pendulum.py --nn_test --shield_test
python cartpole.py --nn_test --shield_test
python selfdriving.py --nn_test --shield_test
python lanekeeping.py --nn_test --shield_test
python 4-car-platoon.py --nn_test --shield_test
python 8-car-platoon.py --nn_test --shield_test
python oscillator.py --nn_test --shield_test
python cartpole_change_l.py --nn_test --shield_test
python pendulum_change_m.py --nn_test --shield_test
python pendulum_change_l.py --nn_test --shield_test
python selfdriving_obs.py --nn_test --shield_test